before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v1
      - linux_arm64
      - linux_386
dockers:
  - image_templates:
      - "ghcr.io/jitsi-contrib/jitsi-exporter:{{.Tag}}"
      - "ghcr.io/jitsi-contrib/jitsi-exporter:latest"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    use: buildx
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
